- name: Install k0s binary
  ansible.builtin.include_role:
    name: k0s_install

- name: Configure k0s controller
  ansible.builtin.import_tasks: configure.yml

- name: Configure container registry
  ansible.builtin.import_tasks: registry.yml

- name: Configure k0s service
  ansible.builtin.import_tasks: service.yml

- name: Remove control-plane scheduling taint
  ansible.builtin.import_tasks: taint.yml

- name: Generate worker join token
  ansible.builtin.import_tasks: token.yml
