- ansible.builtin.import_tasks: os.yml
- ansible.builtin.import_tasks: systemd.yml
- ansible.builtin.import_tasks: ssh.yml
- ansible.builtin.import_tasks: chrony.yml
- ansible.builtin.import_tasks: containerd.yml
