- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
