all:
  children:
    controllers:
      hosts:
        controller-01:
          ansible_host: 192.168.x.x
          ansible_user: <user>        # root (Debian), ubuntu (Ubuntu), nvidia (Jetson)

    workers:
      hosts:
        worker-motion-01:
          ansible_host: 192.168.x.x
          ansible_user: <user>
        worker-perception-01:
          ansible_host: 192.168.x.x
          ansible_user: <user>
        worker-edge-01:
          ansible_host: 192.168.x.x
          ansible_user: <user>
