k0s_install_dir: /usr/local/bin
k0s_config_dir: /etc/k0s

# Fixer une version explicite garantit la cohérence controller/workers
# Laisser commenté pour installer automatiquement la dernière release
# k0s_version: "v1.32.3+k0s.0"

k0s_pod_cidr: 10.244.0.0/16
k0s_service_cidr: 10.96.0.0/12

k0s_cilium_version: "1.16.6"
