- name: Create provisioning manifest directory
  ansible.builtin.file:
    path: /var/lib/k0s/manifests/provisioning
    state: directory
    mode: "0750"

- name: Deploy dnsmasq provisioning manifest
  ansible.builtin.template:
    src: provisioning.yaml.j2
    dest: /var/lib/k0s/manifests/provisioning/dnsmasq.yaml
    mode: "0640"
