[Interface]
Address = 10.0.100.2/24
PrivateKey = YEcAgykZKWobBG/xUkVzviH8QfkGSgLnSsAclXQhr1I=

[Peer]
# controller-01
PublicKey = dLKPSWijnyTiyF4qWiPBDjRsZrCYoYgzEnEF5jr3YiI=
Endpoint = controller-01.local:51820
AllowedIPs = 10.0.100.0/24, 192.168.22.0/24, 192.168.42.0/24, 192.168.62.0/24
PersistentKeepalive = 25
