- name: restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  async: 1
  poll: 0
  ignore_errors: true

- name: restart wpa_supplicant
  ansible.builtin.systemd:
    name: "wpa_supplicant@{{ network_wifi.iface }}"
    state: restarted
